# Generated by Django 6.0.7 on 2026-07-13 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrecord',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='household',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='projectarea',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
