# Generated by Django 6.0.7 on 2026-07-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemanager', '0002_collectionrecord_uid_household_uid_institute_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='last_collection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
