# Generated by Django 6.0.7 on 2026-07-20 11:40
# Manually edited to include a data migration that:
#   1. Creates the Registration table
#   2. Copies all Household rows → Registration (entity_type='household')
#   3. Re-links CollectionRecord.registration_id from the old household_id mapping
#   4. Then safely drops Household and Institute tables

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def copy_households_to_registration(apps, schema_editor):
    """
    Copy every Household row into the new Registration table
    and re-point CollectionRecord rows to the new Registration ID.
    """
    Household         = apps.get_model('wastemanager', 'Household')
    Registration      = apps.get_model('wastemanager', 'Registration')
    CollectionRecord  = apps.get_model('wastemanager', 'CollectionRecord')

    # Map old household primary-key → new registration primary-key
    household_to_registration = {}

    for h in Household.objects.all():
        reg = Registration.objects.create(
            uid                   = h.uid,
            entity_type           = 'household',
            owner_name            = h.owner_name,
            owners_contact        = h.owners_contact,
            district              = h.district,
            ward                  = h.ward,
            village               = h.village,
            house_number          = h.house_number,
            postcode              = h.postcode,
            waste_bin_present     = h.waste_bin_present,
            latitude              = h.latitude,
            longitude             = h.longitude,
            area_id               = h.area_id,
            monthly_fee_override  = h.monthly_fee_override,
            number_of_units       = h.number_of_household,
            last_collection_status = h.last_collection_status,
            last_collection_date  = h.last_collection_date,
            created_by_id         = h.created_by_id,
            updated_by_id         = h.updated_by_id,
        )
        household_to_registration[h.pk] = reg.pk

    # Re-link collection records that were tied to a household
    for record in CollectionRecord.objects.filter(old_household_id__isnull=False):
        new_reg_id = household_to_registration.get(record.old_household_id)
        if new_reg_id:
            record.registration_id = new_reg_id
            record.save(update_fields=['registration_id'])


def noop(apps, schema_editor):
    pass  # No reverse migration for data


class Migration(migrations.Migration):

    dependencies = [
        ('wastemanager', '0003_household_last_collection_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Step 1: Create the unified Registration table ──────────────────────
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(
                    choices=[
                        ('household',   'Household'),
                        ('institute',   'Institute'),
                        ('shop',        'Shop'),
                        ('restaurant',  'Restaurant'),
                        ('hotel',       'Hotel'),
                        ('school',      'School'),
                        ('hospital',    'Hospital'),
                        ('other',       'Other'),
                    ],
                    db_index=True,
                    default='household',
                    max_length=50,
                )),
                ('owner_name',             models.CharField(max_length=255)),
                ('owners_contact',         models.CharField(blank=True, max_length=20, null=True)),
                ('district',               models.CharField(max_length=100)),
                ('ward',                   models.CharField(max_length=100)),
                ('village',                models.CharField(max_length=100)),
                ('house_number',           models.CharField(blank=True, max_length=50)),
                ('postcode',               models.CharField(blank=True, max_length=20)),
                ('waste_bin_present',      models.CharField(max_length=50)),
                ('latitude',               models.FloatField()),
                ('longitude',              models.FloatField()),
                ('monthly_fee_override',   models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_units',        models.IntegerField(default=1)),
                ('last_collection_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_collection_date',   models.DateTimeField(blank=True, null=True)),
                ('area',       models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='wastemanager.projectarea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={'abstract': False},
        ),

        # ── Step 2: Add registration FK to CollectionRecord (nullable for now) ──
        migrations.AddField(
            model_name='collectionrecord',
            name='registration',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='collections',
                to='wastemanager.registration',
            ),
        ),

        # ── Step 3: Rename old household FK to a temporary name so we can still
        #            read it in the RunPython step below ────────────────────────
        migrations.RenameField(
            model_name='collectionrecord',
            old_name='household',
            new_name='old_household',
        ),

        # ── Step 4: Copy data ──────────────────────────────────────────────────
        migrations.RunPython(copy_households_to_registration, reverse_code=noop),

        # ── Step 5: Drop the temporary old household FK ───────────────────────
        migrations.RemoveField(
            model_name='collectionrecord',
            name='old_household',
        ),

        # ── Step 6: Drop the institute FK from CollectionRecord ───────────────
        migrations.RemoveField(
            model_name='collectionrecord',
            name='institute',
        ),

        # ── Step 7: Drop now-empty Institute FK fields and then the model ─────
        migrations.RemoveField(model_name='institute', name='area'),
        migrations.RemoveField(model_name='institute', name='created_by'),
        migrations.RemoveField(model_name='institute', name='updated_by'),
        migrations.DeleteModel(name='Institute'),

        # ── Step 8: Drop the Household model (data already copied) ────────────
        migrations.DeleteModel(name='Household'),
    ]
