# Generated by Django 6.0.7 on 2026-07-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemanager', '0004_unify_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrecord',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('collected and paid', 'Collected and Paid'), ('missed', 'Missed'), ('unpaid', 'Unpaid')], max_length=20),
        ),
    ]
