# Generated by Django 6.0.7 on 2026-07-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastemanager', '0005_alter_collectionrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
